# Generated by Django 5.0.7 on 2024-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0003_bank_exchangerate_date_exchangerate_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ቤንዚን", "ቤንዚን (Benzine)"),
                            ("ናፍጣ", "ናፍጣ (Naphtha)"),
                            ("ኬሮሲን", "ኬሮሲን (Kerosene)"),
                            ("የአውሮፕላን ነዳጅ", "የአውሮፕላን ነዳጅ (Aviation Fuel)"),
                            ("ቀላል ጥቁር ናፍጣ", "ቀላል ጥቁር ናፍጣ (Light Black Naphtha)"),
                            ("ከባድ ጥቁር ናፍጣ", "ከባድ ጥቁር ናፍጣ (Heavy Black Naphtha)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
            ],
        ),
    ]
