# Generated by Django 5.0.7 on 2024-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0004_fuel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["bank", "currency", "date"],
                name="exchange_ra_bank_id_653d70_idx",
            ),
        ),
    ]
